sudo: required
dist: xenial

language: go
go:
  - "1.11.4"

notifications:
  email:
    recipients:
      - ed.nmi.oakes@gmail.com
      - tylerharter@gmail.com

install:
  - sudo ./quickstart/deps.sh

script:
  - sudo make
