enableAllRules = true
errorCode = 2
#warningCode = 1

#TODO we should eventually comment all public methods
[rule.package-comments]
    Disabled = true

#TODO get rid of all (or most) magic numbers
[rule.add-constant]
    Disabled = true

#TODO we should handle all errors
[rule.unhandled-error]
    Disabled = true

#TODO use uniform casing everywhere
[rule.var-naming]
    Disabled = true

[rule.defer]
    Disabled = true
[rule.empty-block]
    Disabled = true
[ruile.var-declaration]
    Disabled = true
[rule.confusing-results]
    Disabled = true
[rule.call-to-gc]
    Disabled = true
[rule.import-shadowing]
    Disabled = true
[rule.receiver-naming]
    Disabled = true
[rule.error-strings]
    Disabled = true
[rule.exported]
    Disabled = true
[rule.early-return]
    Disabled = true
[rule.deep-exit]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.file-header]
    Disabled = true
[rule.banned-characters]
    Disabled = true
[rule.max-public-structs]
    Disabled = true
[rule.line-length-limit]
    Disabled = true
[rule.cognitive-complexity]
    Disabled = true
[rule.increment-decrement]
    Disabled = true
[rule.flag-parameter]
    Disabled = true

[rule.argument-limit]
    Arguments = [7]

# TODO reduce to 10 or so
[rule.cyclomatic]
    Arguments = [35]
[rule.function-result-limit]
    Arguments = [3]
